"""
Phase 34.5 -- Annual Automated Order System Attestation
US + Canada Market Intelligence Platform

CIRO / UMIR Policy 7.1 Part 8 requires that an automated order system be tested before use
and **at least annually**, with a written record; that the Participant be able to override
or disable it immediately; and that the Participant remain responsible for its orders
including "runaway algo" behaviour.

This module produces that written record. It is a genuine compliance artifact rather than
theatre: the attestation is generated by actually running the control-coverage suite and
recording what passed, what failed, and which code version was tested. An attestation that
merely asserted "we tested it" would not be a record of anything.

What is attested, and what is not:

  - ATTESTED: every pre-trade control C1..C12 is registered and exercised by a test; the
    routing gates (Canadian firewall, license, capability) are exercised; the state machine
    is exercised; the kill switch can actually halt routing; the execution test suites pass.
  - NOT ATTESTED: profitability, fill-quality realism, or suitability of any signal. This
    platform is unregistered impersonal research and makes no such claim.
"""

import hashlib
import json
import os
import subprocess
from dataclasses import dataclass, field, asdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional

from config.settings import BASE_DIR, DATA_DIR
from src.data.db import Database, db as _default_db
from src.execution.risk_governor import CONTROL_REGISTRY
from src.execution.state_machine import LEGAL_TRANSITIONS

ATTESTATION_DIR = DATA_DIR / "attestations"
ATTESTATION_VALIDITY_DAYS = 365

# The execution suites that constitute the control-coverage evidence.
EXECUTION_TEST_SUITES = [
    "tests/test_execution_order_lifecycle.py",
    "tests/test_execution_risk_governor.py",
    "tests/test_execution_internal_simulator.py",
    "tests/test_execution_router.py",
    "tests/test_execution_telemetry.py",
    # Included deliberately: an attestation whose evidence set omits its own tests would
    # understate coverage. See REENTRANCY_GUARD_ENV -- the suite is written so that running
    # it inside an attestation does not start another attestation.
    "tests/test_execution_aos_feed.py",
]

# Set in the environment of the pytest subprocesses. The attestation suite checks for it and
# skips the one test that would otherwise invoke run_attestation(run_tests=True) again,
# which would recurse until the process died. A guard rather than an omission, so the
# evidence set stays complete.
REENTRANCY_GUARD_ENV = "AOS_ATTESTATION_IN_PROGRESS"


@dataclass
class AosAttestation:
    """One annual testing record."""
    year: int
    attested_at: str
    code_version: str
    controls_registered: int = 0
    controls_with_tests: int = 0
    controls_without_tests: List[str] = field(default_factory=list)
    routing_gates_checked: int = 0
    state_machine_edges: int = 0
    kill_switch_verified: bool = False
    tests_passed: int = 0
    tests_failed: int = 0
    suites_run: int = 0
    passed: bool = False
    artifact_path: str = ""
    scope_note: str = ""

    @property
    def days_until_expiry(self) -> int:
        """
        Days remaining before Policy 7.1 Part 8 requires re-testing.

        Returns -1 when the attestation date cannot be parsed. A record whose date is
        unreadable cannot be shown to be current, so it must read as expired rather than
        silently valid -- failing closed is the only safe answer for a compliance artifact.
        """
        try:
            attested = datetime.fromisoformat(self.attested_at)
        except ValueError:
            return -1
        elapsed = (datetime.now(timezone.utc) - attested).days
        return ATTESTATION_VALIDITY_DAYS - elapsed

    @property
    def expired(self) -> bool:
        return self.days_until_expiry < 0

    def to_dict(self) -> Dict[str, Any]:
        d = asdict(self)
        d["days_until_expiry"] = self.days_until_expiry
        d["expired"] = self.expired
        return d


# --------------------------------------------------------------------------------------
# Evidence collection
# --------------------------------------------------------------------------------------

def _git_revision() -> str:
    """The commit the suite was run against. Unavailable is recorded, not guessed."""
    try:
        out = subprocess.run(
            ["git", "rev-parse", "HEAD"], cwd=str(BASE_DIR),
            capture_output=True, text=True, timeout=15,
        )
        if out.returncode == 0:
            return out.stdout.strip()
    except Exception:
        pass
    return "UNKNOWN"


def _controls_with_test_coverage() -> Dict[str, bool]:
    """
    Checks that each registered control is named in the governor test suite.

    Matching on the control id is a coverage proxy, not a proof of correctness: it verifies
    a test mentions the control, which is necessary but not sufficient. Recorded as such.
    """
    suite = BASE_DIR / "tests" / "test_execution_risk_governor.py"
    text = suite.read_text(encoding="utf-8") if suite.exists() else ""
    # Strip comments so an explanatory comment cannot masquerade as coverage.
    code = "\n".join(line.split("#")[0] for line in text.splitlines())
    return {c.control_id: (f'"{c.control_id}"' in code or f"'{c.control_id}'" in code
                           or f"{c.control_id.lower()}(" in code)
            for c in CONTROL_REGISTRY}


def _verify_kill_switch(db: Database) -> bool:
    """
    Confirms the kill switch can actually halt routing and be reversed. An attestation that
    claimed this without exercising it would be asserting the one control whose failure
    mode is catastrophic.
    """
    from src.execution.order_model import Market, OrderRequest, OrderSide, OrderType, \
        build_client_order_id
    from src.execution.router import KILL_ALL, AdapterRegistry, AdapterRouter, KillSwitch
    from src.execution.adapters.internal_simulator import InternalSimulatorAdapter
    from src.execution.state_machine import ExecutionLedger
    from datetime import date

    ks = KillSwitch(db=db)
    reg = AdapterRegistry()
    reg.register(InternalSimulatorAdapter(ledger=ExecutionLedger(db=db), db=db))
    rt = AdapterRouter(registry=reg, kill_switch=ks)

    req = OrderRequest(
        client_order_id=build_client_order_id("ZZTEST", "BUY", 1, "MARKET", "AOS",
                                              date(2026, 1, 1)),
        symbol="ZZTEST", market=Market.US, side=OrderSide.BUY, quantity=1,
        order_type=OrderType.MARKET, signal_date=date(2026, 1, 1),
    )
    ks.engage(KILL_ALL, reason="AOS attestation self-test")
    try:
        halted = rt.route(req).allowed is False
    finally:
        ks.disengage(KILL_ALL, reason="AOS attestation self-test")
    restored = rt.route(req).allowed is True
    return halted and restored


def _run_test_suites() -> Dict[str, Any]:
    """Runs the execution suites and returns pass/fail counts."""
    passed = failed = suites = 0
    for suite in EXECUTION_TEST_SUITES:
        if not (BASE_DIR / suite).exists():
            continue
        try:
            env = {**os.environ, REENTRANCY_GUARD_ENV: "1"}
            out = subprocess.run(
                ["python3", "-m", "pytest", suite, "-q", "--no-header", "-p", "no:cacheprovider"],
                cwd=str(BASE_DIR), capture_output=True, text=True, timeout=900, env=env,
            )
            tail = out.stdout.strip().splitlines()[-1] if out.stdout.strip() else ""
            suites += 1
            for token in tail.replace(",", " ").split():
                if token.isdigit():
                    n = int(token)
                elif token == "passed":
                    passed += n
                elif token in ("failed", "errors"):
                    failed += n
        except Exception:
            suites += 1
            failed += 1
    return {"passed": passed, "failed": failed, "suites": suites}


# --------------------------------------------------------------------------------------
# Attestation
# --------------------------------------------------------------------------------------

def run_attestation(db: Optional[Database] = None, year: Optional[int] = None,
                    run_tests: bool = True) -> AosAttestation:
    """
    Runs the control-coverage suite, writes the JSON artifact, and records the row.

    `passed` is True only when every registered control has coverage, the kill switch was
    verified live, and no test failed. A partial result is recorded as a failed
    attestation rather than silently rounded up.
    """
    conn = db or _default_db
    year = year or datetime.now(timezone.utc).year
    now = datetime.now(timezone.utc)

    coverage = _controls_with_test_coverage()
    without = sorted(cid for cid, ok in coverage.items() if not ok)

    ks_ok = _verify_kill_switch(conn)
    tests = _run_test_suites() if run_tests else {"passed": 0, "failed": 0, "suites": 0}

    att = AosAttestation(
        year=year,
        attested_at=now.isoformat(),
        code_version=_git_revision(),
        controls_registered=len(CONTROL_REGISTRY),
        controls_with_tests=sum(1 for ok in coverage.values() if ok),
        controls_without_tests=without,
        routing_gates_checked=5,   # firewall, license, capability, configured, market
        state_machine_edges=sum(len(v) for v in LEGAL_TRANSITIONS.values()),
        kill_switch_verified=ks_ok,
        tests_passed=tests["passed"],
        tests_failed=tests["failed"],
        suites_run=tests["suites"],
        scope_note=(
            "Attests pre-trade control coverage, routing gates, state-machine integrity and "
            "kill-switch operation only. Does not attest profitability, fill-quality "
            "realism, or the suitability of any signal. Unregistered impersonal research; "
            "no external broker adapter ships and no order routes to a live venue."
        ),
    )
    att.passed = (not without) and ks_ok and tests["failed"] == 0 and tests["suites"] > 0

    ATTESTATION_DIR.mkdir(parents=True, exist_ok=True)
    artifact = ATTESTATION_DIR / f"aos_{year}.json"
    with open(artifact, "w", encoding="utf-8") as f:
        json.dump(att.to_dict(), f, indent=2)
    att.artifact_path = str(artifact)

    _ensure_table(conn)
    conn.execute_write(
        """
        INSERT INTO aos_attestation
            (year, attested_at, code_version, controls_registered, controls_with_tests,
             controls_without_tests, routing_gates_checked, state_machine_edges,
             kill_switch_verified, tests_passed, tests_failed, suites_run, passed,
             artifact_path, scope_note)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        ON CONFLICT(year) DO UPDATE SET
            attested_at=excluded.attested_at,
            code_version=excluded.code_version,
            controls_registered=excluded.controls_registered,
            controls_with_tests=excluded.controls_with_tests,
            controls_without_tests=excluded.controls_without_tests,
            routing_gates_checked=excluded.routing_gates_checked,
            state_machine_edges=excluded.state_machine_edges,
            kill_switch_verified=excluded.kill_switch_verified,
            tests_passed=excluded.tests_passed,
            tests_failed=excluded.tests_failed,
            suites_run=excluded.suites_run,
            passed=excluded.passed,
            artifact_path=excluded.artifact_path,
            scope_note=excluded.scope_note;
        """,
        (att.year, att.attested_at, att.code_version, att.controls_registered,
         att.controls_with_tests, json.dumps(without), att.routing_gates_checked,
         att.state_machine_edges, 1 if att.kill_switch_verified else 0,
         att.tests_passed, att.tests_failed, att.suites_run, 1 if att.passed else 0,
         att.artifact_path, att.scope_note),
    )
    return att


def _ensure_table(conn: Database) -> None:
    conn.execute_write(
        """
        CREATE TABLE IF NOT EXISTS aos_attestation (
            year                   INTEGER PRIMARY KEY,
            attested_at            TEXT    NOT NULL,
            code_version           TEXT    NOT NULL,
            controls_registered    INTEGER NOT NULL,
            controls_with_tests    INTEGER NOT NULL,
            controls_without_tests TEXT,
            routing_gates_checked  INTEGER NOT NULL,
            state_machine_edges    INTEGER NOT NULL,
            kill_switch_verified   INTEGER NOT NULL,
            tests_passed           INTEGER NOT NULL,
            tests_failed           INTEGER NOT NULL,
            suites_run             INTEGER NOT NULL,
            passed                 INTEGER NOT NULL,
            artifact_path          TEXT,
            scope_note             TEXT
        );
        """
    )


def latest_attestation(db: Optional[Database] = None) -> Optional[AosAttestation]:
    """Most recent record, or None if the system has never been attested."""
    conn = db or _default_db
    try:
        _ensure_table(conn)
        rows = conn.execute_query(
            "SELECT * FROM aos_attestation ORDER BY year DESC, attested_at DESC LIMIT 1;"
        )
    except Exception:
        return None
    if not rows:
        return None
    r = rows[0]
    try:
        without = json.loads(r["controls_without_tests"] or "[]")
    except (TypeError, ValueError):
        without = []
    att = AosAttestation(
        year=int(r["year"]), attested_at=r["attested_at"], code_version=r["code_version"],
        controls_registered=int(r["controls_registered"]),
        controls_with_tests=int(r["controls_with_tests"]),
        controls_without_tests=without,
        routing_gates_checked=int(r["routing_gates_checked"]),
        state_machine_edges=int(r["state_machine_edges"]),
        kill_switch_verified=bool(r["kill_switch_verified"]),
        tests_passed=int(r["tests_passed"]), tests_failed=int(r["tests_failed"]),
        suites_run=int(r["suites_run"]), passed=bool(r["passed"]),
        artifact_path=r["artifact_path"] or "", scope_note=r["scope_note"] or "",
    )
    return att


def artifact_digest(path: Optional[str] = None) -> str:
    """SHA-256 of the attestation artifact, so the record can be tied to its evidence."""
    if not path or not Path(path).exists():
        return ""
    return hashlib.sha256(Path(path).read_bytes()).hexdigest()


__all__ = [
    "AosAttestation",
    "ATTESTATION_DIR",
    "ATTESTATION_VALIDITY_DAYS",
    "EXECUTION_TEST_SUITES",
    "REENTRANCY_GUARD_ENV",
    "run_attestation",
    "latest_attestation",
    "artifact_digest",
]
